name: document
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0
  google_sign_in: ^6.1.0
  path_provider: ^2.1.1
  open_file: ^3.3.2
  universal_html: ^2.2.4
  uuid: ^3.0.7
  audioplayers: ^5.2.1
  firebase_database: ^11.3.1
  permission_handler: ^10.4.3
  share: ^2.0.4
  downloads_path_provider_28: ^0.1.2
  path: ^1.8.0
  cupertino_icons: ^1.0.8
  postgres: ^2.4.3
  firebase_auth: ^5.4.0
  firebase_storage: ^12.4.0
  firebase_messaging: ^15.2.0
  firebase_core: ^3.10.0
  shared_preferences: ^2.1.6
  file_picker: ^5.0.0
  syncfusion_flutter_pdfviewer: ^23.1.39
  flutter_staggered_grid_view: ^0.6.2
  animations: ^2.0.0
  share_plus: ^7.0.0
  url_launcher: ^6.1.102
  video_player: ^2.9.2
  web3dart: ^2.7.1
  http: ^1.3.0
  file: ^6.1.4
  cloud_firestore: 5.6.2
  googleapis: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
    - assets/sounds/success.mp3
