# Generated by Django 5.1.5 on 2025-01-31 00:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/', validators=[api.models.validate_file_extension])),
                ('filename', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('lobby_name', models.CharField(max_length=255)),
                ('uploader', models.CharField(max_length=255)),
            ],
        ),
    ]
