# Generated by Django 5.1.5 on 2025-02-02 01:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_document_drive_link_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='drive_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[api.models.validate_file_extension]),
        ),
    ]
