# Generated by Django 5.1.5 on 2025-02-03 05:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_document_drive_link_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='drive_link',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(default=1, upload_to='documents/', validators=[api.models.validate_file_extension]),
            preserve_default=False,
        ),
    ]
